# Generated by Django 3.2.9 on 2021-11-24 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0003_auto_20211124_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
