# Generated by Django 3.2.9 on 2021-11-24 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0005_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
