# Generated by Django 3.2.9 on 2021-11-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0014_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='token',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
