# Generated by Django 3.2.9 on 2021-11-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0015_customer_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Available_hrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Opening_time', models.TimeField(null=True)),
                ('Closing_time', models.TimeField(null=True)),
            ],
        ),
    ]
