# Generated by Django 3.2.9 on 2021-11-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bakery', '0014_customer_token'),
        ('Bakery', '0016_available_hrs'),
    ]

    operations = [
    ]
